# Generated by Django 5.2.17 on 2026-09-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_id_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer_mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
