# Generated by Django 5.2.17 on 2026-09-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_organizer_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_team_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='min_team_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='participation_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual', max_length=20),
        ),
    ]
