# Generated by Django 6.1.1 on 2026-09-27 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('events', '0002_event_max_team_size_event_min_team_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(blank=True, max_length=255)),
                ('department_name', models.CharField(blank=True, max_length=255)),
                ('institute_logo', models.ImageField(blank=True, null=True, upload_to='certificate_assets/institute/')),
                ('certificate_heading', models.CharField(blank=True, default='CERTIFICATE', max_length=100)),
                ('certificate_subheading', models.CharField(blank=True, default='OF PARTICIPATION', max_length=100)),
                ('presentation_text', models.CharField(blank=True, default='THIS CERTIFICATE IS PROUDLY PRESENTED TO', max_length=255)),
                ('participation_text', models.CharField(blank=True, default='for actively participating in the event', max_length=255)),
                ('organized_by_text', models.CharField(blank=True, default='organized by EventHub, College Events.', max_length=255)),
                ('event_title', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('event_venue', models.CharField(blank=True, max_length=255)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('sponsor_name', models.CharField(blank=True, max_length=255)),
                ('sponsor_logo', models.ImageField(blank=True, null=True, upload_to='certificate_assets/sponsors/')),
                ('coordinator_name', models.CharField(blank=True, max_length=150)),
                ('coordinator_designation', models.CharField(blank=True, default='Event Coordinator', max_length=150)),
                ('coordinator_signature', models.ImageField(blank=True, null=True, upload_to='certificate_assets/signatures/')),
                ('head_name', models.CharField(blank=True, max_length=150)),
                ('head_designation', models.CharField(blank=True, default='Head of Department', max_length=150)),
                ('head_signature', models.ImageField(blank=True, null=True, upload_to='certificate_assets/signatures/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_configuration', to='events.event')),
            ],
            options={
                'verbose_name': 'Certificate Configuration',
                'verbose_name_plural': 'Certificate Configurations',
            },
        ),
    ]
